create table Tabela_Lavanderia
(
    id                    bigint generated by default as identity,
    nome_lavanderia       varchar(50) NOT NULL,
    endereco_lavanderia   varchar(100),
    numero_lavanderia     numeric (1000),
    bairro_lavanderia     varchar(30) NOT NULL,
    zona_lavanderia       varchar(20),
    primary key (id)
);